apiVersion: apps/v1
kind: Deployment
metadata:
  name: swap-uniba-llm-wsd-ft-all
  namespace: bdarabisahneh
  labels:
    app: swap-uniba-llm-wsd-ft-all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swap-uniba-llm-wsd-ft-all
  template:
    metadata:
      labels:
        app: swap-uniba-llm-wsd-ft-all
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: swap-uniba-llm-wsd-ft-all
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      nodeSelector:
        gpu: a100
      containers:
      - name: swap-uniba-llm-wsd-ft-all
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve swap-uniba/LLM-wsd-FT-ALL --trust-remote-code --enable-chunked-prefill --max_num_batched_tokens 1024"
        ]
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "10"
            memory: 20G
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 6G
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
