apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swap-uniba-llm-wsd-ft-all
  namespace: bdarabisahneh
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
