apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perturbation-experiments-pvc
  namespace: bdarabisahneh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: shared
