apiVersion: v1
kind: Service
metadata:
  name: meta-llama-llama-3-2-1b-instruct
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: meta-llama-llama-3-2-1b-instruct 