apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache
  namespace: bdarabisahneh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: shared
  