apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-oss-120b
  namespace: bdarabisahneh
  labels:
    app: gpt-oss-120b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-oss-120b
  template:
    metadata:
      labels:
        app: gpt-oss-120b
    spec:
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: vllm-cache
        # vLLM needs to access the host's shared memory for tensor parallel inference.
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
      nodeSelector:
        gpu: a100
      containers:
        - name: gpt-oss-120b
          image: vllm/vllm-openai:v0.10.2
          command: ["/bin/sh", "-c"]
          args:
            [
              "vllm serve openai/gpt-oss-120b --trust-remote-code --enable-chunked-prefill --gpu-memory-utilization 0.9 --tensor-parallel-size 4 --max_num_batched_tokens 1024 --max_model_len 10000",
            ]
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hugging-face-hub-token
                  key: token
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "10"
              memory: 20G
              nvidia.com/gpu: "4"
            requests:
              cpu: "2"
              memory: 6G
              nvidia.com/gpu: "4"
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: cache-volume
            - name: shm
              mountPath: /dev/shm
